version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200