version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    command:
      - /bin/bash
      - -c
      - |
        bin/elasticsearch-plugin install analysis-stempel
        bin/elasticsearch
volumes:
  qdrant_data:
  elasticsearch_data: