version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    command:
      - /bin/bash
      - -c
      - |
        bin/elasticsearch-plugin install analysis-stempel
        bin/elasticsearch-plugin install pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:8.12.2
        bin/elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    ports:
      - 5601:5601
    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          memory: 2g
volumes:
  qdrant_data:
  elasticsearch_data:
  kibana_data:
  mongo_data: